name: local_settings
description: A basic shared_preferences layer for Flutter apps
version: 1.0.0
repository: https://github.com/sadespresso/local_settings
issue_tracker: https://github.com/sadespresso/local_settings/issues

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  shared_preferences: ^2.5.2
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.2
