name: local_settings
description: A basic shared_preferences layer for Flutter apps
version: 0.2.2
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^2.17.0

dependencies:
  shared_preferences: ^2.0.16
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.2
